
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://dishbreak.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "Vishal Kotcherlakota"
title: "{ Vishal Kotcherlakota }"
description: "Blog and website of Vishal Kotcherlakota, blogging mainly for tech. Opinions expressed are mine."
keywords: "Kotcherlakota, vishal, github, jekyll"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/keyboard.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Learn how everything is put together by paying attention when things fall apart."
  - text: "Engineering is about bridging the gap between <i>should</i> and <i>does</i>."
  - text: "You're at your best when you're doing something you've never done before."

me-img: "/img/vishal.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: False
google-plus-share: False
tumblr-share: True
pinterest-share: False
pocket-share: True
vkontakte-share: False

disqus-shortname: "dishbreak"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: ""
    date: "December 2018 - Present"
    description: "Staff DevOps Engineer at NerdWallet"
  - image: ""
    date: "Februrary 2017 - November 2018"
    description: "DevOps / Software Engineering at QuanticMind"
  - image: ""
    date: "September 2012 - June 2015"
    description: "Attended University of California, Los Angeles (M.S. Engineering, Computer Networks)"
  - image: ""
    date: "June 2009 - Februrary 2017"
    description: "Systems/Software Engineering at Lockheed Martin"
  - image: ""
    date: "September 2006 - June 2010"
    description: "Attended University of California, San Diego (B.S. Electrical Engineering)"

# First image of the Timeline

timeline-img: "/img/vishal.jpg"

###########
# Contact #
###########

email: "vishal@kotcherlakota.org"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Vishal Kotcherlakota is a reformed sysadmin, who writes code and will talk incessantly about DevOps to anyone who will listen. All views expressed here are his and not those of his employers."
author_blurb_image: "/img/vishal.jpg"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/dishbreak"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/vishalkotcherlakota"
  - title: "stack-overflow"
    url: "http://stackoverflow.com/users/225905/vishal-kotcherlakota"
############
# 404 page #
############

404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: johnsmith
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Projects: 'projects'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
